import React, { useEffect, useState } from "react";
import { useNavigate, useLocation } from "react-router-dom";
import AppShell from "../components/AppShell.jsx";
import Button from "../components/Button.jsx";
import { useAuth } from "../lib/useAuth.js";
import { getPhotoThumbUrls } from "../lib/projectPhotoLog.js";

const COMPANY = {
  name: "XA GLASS INSTALLATION SERVICES",
  address: "Blk 3 Lot 2 Silmer Village Brgy San Francisco, Binan, Laguna",
  email: "queries@xaglass.com.ph",
  phone: "0927.960.2672 | 0953.239.1609",
};

// Custom report generator output. Printed via window.print() on a
// dedicated print-area (see index.css) -- no PDF library needed, every
// OS/browser can "Print > Save as PDF" natively.
export default function Report({ project }) {
  const navigate = useNavigate();
  const location = useLocation();
  const { appUser } = useAuth();

  const selectedPhotos = location.state?.photos || [];

  const [imageUrls, setImageUrls] = useState({});
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    if (selectedPhotos.length === 0) { setLoading(false); return; }
    getPhotoThumbUrls(selectedPhotos.map((p) => p.image_path).filter(Boolean))
      .then(setImageUrls)
      .catch((err) => setError(err.message))
      .finally(() => setLoading(false));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const today = new Date().toLocaleDateString("en-PH", { year: "numeric", month: "long", day: "numeric" });

  if (selectedPhotos.length === 0) {
    return (
      <AppShell project={project} title="Photo Report" onBack={() => navigate("/browse")}>
        <p className="text-sm text-text-tertiary text-center py-10">
          No photos selected. Go back to Search &amp; Filter and pick photos to include in a report.
        </p>
      </AppShell>
    );
  }

  return (
    <AppShell project={project} title="Photo Report" onBack={() => navigate("/browse")}>
      {loading && <p className="text-sm text-text-tertiary text-center py-10">Loading...</p>}
      {error && <p className="text-sm text-status-red text-center py-10">{error}</p>}

      {!loading && !error && (
        <>
          <div className="flex justify-end mb-4 print:hidden">
            <Button size="sm" onClick={() => window.print()}>Print / Save as PDF</Button>
          </div>

          <div id="photolog-print-area" className="bg-white text-black rounded-card p-6 max-w-4xl mx-auto shadow-sm print:shadow-none print:p-0 print:max-w-full text-[13px] leading-snug">
            <div className="flex items-start justify-between mb-4 pb-3 border-b-2 border-gray-800">
              <div>
                <h1 className="text-lg font-bold tracking-tight">{COMPANY.name}</h1>
                <p className="text-xs text-gray-500 mt-0.5">Project Photo Report — One Lens, One Data</p>
              </div>
              <div className="text-right text-xs text-gray-600">
                <p>{COMPANY.address}</p>
                <p>{COMPANY.email}</p>
                <p>{COMPANY.phone}</p>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-x-8 gap-y-1 mb-5 text-xs border border-gray-300 p-3">
              <div><span className="font-semibold">Project:</span> {project?.description || project?.project_code || "—"}</div>
              <div><span className="font-semibold">Date Generated:</span> {today}</div>
              <div><span className="font-semibold">Site Location:</span> {project?.site_location || "—"}</div>
              <div><span className="font-semibold">Generated By:</span> {appUser?.employee?.full_name || appUser?.employee_code}</div>
              <div><span className="font-semibold">Project Code:</span> {project?.project_code || "—"}</div>
              <div><span className="font-semibold">Photos Included:</span> {selectedPhotos.length}</div>
            </div>

            <div className="space-y-5">
              {selectedPhotos.map((p) => (
                <div key={p.id} className="border border-gray-300 rounded p-3 break-inside-avoid">
                  <div className="flex gap-4">
                    {imageUrls[p.image_path] && (
                      <img
                        src={imageUrls[p.image_path]}
                        alt={p.photo_id}
                        className="w-40 h-40 object-cover rounded border border-gray-300 shrink-0"
                      />
                    )}
                    <div className="min-w-0 flex-1 text-xs space-y-1">
                      <p className="font-semibold text-sm">{p.photo_id}</p>
                      <p><span className="font-semibold">Location:</span> {p.floor_level || "—"} {p.unit_number ? `· Unit ${p.unit_number}` : ""}</p>
                      <p><span className="font-semibold">Scope of Work:</span> {(p.scope_of_work || []).join(", ") || "—"}</p>
                      <p><span className="font-semibold">Photo Category:</span> {(p.photo_category || []).join(", ") || "—"}</p>
                      {p.remarks && <p><span className="font-semibold">Remarks:</span> {p.remarks}</p>}
                      <p><span className="font-semibold">Submitted By:</span> {p.submitted_by?.employee?.full_name || p.submitted_by?.employee_code || "—"} ({p.submitted_by?.roles?.role_name || "—"})</p>
                      <p><span className="font-semibold">Date:</span> {new Date(p.created_at).toLocaleString()}</p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </>
      )}
    </AppShell>
  );
}
